apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 30m
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
