apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
